spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

  kafka:
    bootstrap-servers: localhost:29092
    topic:
      registration: registration-topic
      verification: verification-topic
    consumer:
      group-id: registration

custom:
  statuses:
    pending: PENDING
    processed: PROCESSED
  eventTypes:
    userRegistered: USER_REGISTERED